import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import * as Lucide from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { api } from "@/lib/api";
import { toast } from "sonner";

export const Route = createFileRoute("/app/sql")({
  component: SQLPage,
});

interface Feature {
  name: string;
  iconName?: string;
  phase: string;
  subs: string[];
  tasks?: string[];
  sqlSchema?: string[];
}

interface SQLGenerationStatus {
  featureIdx: number;
  status: "idle" | "generating" | "done" | "error";
  generatedSQL?: string;
}

function SQLPage() {
  const navigate = useNavigate();
  const [projectName, setProjectName] = useState("Proyek Aplikasi");
  const [features, setFeatures] = useState<Feature[]>([]);
  const [loading, setLoading] = useState(true);
  const [generatingAll, setGeneratingAll] = useState(false);
  const [sqlStatuses, setSqlStatuses] = useState<SQLGenerationStatus[]>([]);
  const [expandedIdx, setExpandedIdx] = useState<number | null>(null);
  const [copiedIdx, setCopiedIdx] = useState<number | null>(null);

  useEffect(() => {
    async function load() {
      const projectId = localStorage.getItem("active_project_id");
      if (!projectId) { setLoading(false); return; }
      try {
        const proj = await api.projects.get(projectId);
        if (proj) setProjectName(proj.name);
        const canvas = await api.projects.getCanvas(projectId);
        if (canvas && canvas.features && canvas.features.length > 0) {
          setFeatures(canvas.features);
          setSqlStatuses(canvas.features.map((_: Feature, i: number) => ({ featureIdx: i, status: "idle" as const })));
        }
      } catch (err) { console.error(err); }
      finally { setLoading(false); }
    }
    load();
  }, []);

  function getAllSQL(): string {
    let sql = `-- ==========================================\n-- ${projectName.toUpperCase()} - COMPLETE SQL DATABASE SCHEMAS\n-- Generated by AI Workflow Studio (Gemini + Groq)\n-- ==========================================\n\n`;
    features.forEach((feat, idx) => {
      sql += `-- ==========================================\n-- MODULE: ${feat.name.toUpperCase()}\n-- Phase: ${feat.phase}\n-- ==========================================\n\n`;
      const status = sqlStatuses[idx];
      const schemas = status?.generatedSQL
        ? [status.generatedSQL]
        : (feat.sqlSchema ?? []);
      schemas.forEach((s) => { sql += s + "\n\n"; });
    });
    return sql;
  }

  function getFeatureSQL(idx: number): string {
    const status = sqlStatuses[idx];
    const feat = features[idx];
    if (status?.generatedSQL) return status.generatedSQL;
    return (feat?.sqlSchema ?? []).join("\n\n");
  }

  async function generateSQLForFeature(idx: number) {
    const projectId = localStorage.getItem("active_project_id");
    if (!projectId) return;
    const feat = features[idx];

    setSqlStatuses((prev) =>
      prev.map((s, i) => i === idx ? { ...s, status: "generating" } : s)
    );

    try {
      // Build a focused SQL-generation prompt via the generate endpoint
      const provider = localStorage.getItem("active_provider") ?? "collaborative";
      const result = await api.generate.canvas(projectId, {
        provider,
        revision: `Generate ONLY SQL CREATE TABLE statements (up to 5000 characters) for the feature: "${feat.name}". Sub-features include: ${feat.subs.join(", ")}. Include all necessary tables with proper UUID primary keys, foreign keys, indexes, constraints, and TIMESTAMPTZ columns. Output ONLY raw SQL, no explanations, no markdown code blocks.`,
      });

      if (result && result.content) {
        // Try to extract SQL from the canvas JSON response or use raw
        let sqlText = result.content;
        try {
          const cleaned = sqlText.replace(/```json/g, "").replace(/```sql/g, "").replace(/```/g, "").trim();
          // If it's JSON array (canvas), extract sqlSchema
          const parsed = JSON.parse(cleaned);
          if (Array.isArray(parsed) && parsed[0]?.sqlSchema) {
            sqlText = parsed.map((f: Feature) => (f.sqlSchema ?? []).join("\n\n")).join("\n\n");
          } else if (parsed?.content) {
            sqlText = parsed.content;
          }
        } catch {
          // It's raw SQL text — use as-is
          sqlText = result.content.replace(/```sql/g, "").replace(/```/g, "").trim();
        }

        setSqlStatuses((prev) =>
          prev.map((s, i) => i === idx ? { ...s, status: "done", generatedSQL: sqlText } : s)
        );
        toast.success(`SQL untuk "${feat.name}" berhasil digenerate!`);
      }
    } catch (err) {
      console.error(err);
      setSqlStatuses((prev) =>
        prev.map((s, i) => i === idx ? { ...s, status: "error" } : s)
      );
      toast.error(`Gagal generate SQL untuk "${feat.name}".`);
    }
  }

  async function generateAllSQL() {
    setGeneratingAll(true);
    for (let i = 0; i < features.length; i++) {
      await generateSQLForFeature(i);
      // Small delay between calls to avoid rate limiting
      await new Promise((res) => setTimeout(res, 800));
    }
    setGeneratingAll(false);
    toast.success("Semua SQL berhasil digenerate!");
  }

  async function copySQL(idx: number) {
    const sql = getFeatureSQL(idx);
    try {
      await navigator.clipboard.writeText(sql);
      setCopiedIdx(idx);
      setTimeout(() => setCopiedIdx(null), 2000);
      toast.success("SQL disalin ke clipboard!");
    } catch { toast.error("Gagal menyalin SQL."); }
  }

  async function copyAllSQL() {
    try {
      await navigator.clipboard.writeText(getAllSQL());
      toast.success("Semua SQL disalin ke clipboard!");
    } catch { toast.error("Gagal menyalin."); }
  }

  function downloadAllSQL() {
    const blob = new Blob([getAllSQL()], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${projectName.replace(/\s+/g, "_")}_Complete_SQL.sql`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("File SQL berhasil diunduh!");
  }

  const totalTables = features.reduce((acc, f) => acc + (f.sqlSchema?.length ?? 0), 0);

  return (
    <div className="flex h-screen flex-col overflow-hidden bg-background">
      {/* Header */}
      <div className="flex items-center justify-between border-b border-border bg-card/50 px-6 py-3 backdrop-blur-md">
        <div className="flex items-center gap-3">
          <button
            onClick={() => navigate({ to: "/app/canvas" })}
            className="flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground transition"
          >
            <Lucide.ArrowLeft size={13} /> Canvas
          </button>
          <span className="text-muted-foreground">/</span>
          <div className="flex items-center gap-2 text-sm font-semibold text-foreground">
            <Lucide.Database size={15} className="text-emerald-400" />
            SQL Database Schemas
          </div>
        </div>
        <div className="flex items-center gap-2">
          <span className="text-xs text-muted-foreground hidden sm:block">
            {features.length} modul · {totalTables} tabel terencana
          </span>
          <Button
            onClick={copyAllSQL}
            variant="outline" size="sm"
            className="text-xs border-slate-700 hover:bg-slate-800 gap-1.5"
          >
            <Lucide.Copy size={13} /> Copy Semua
          </Button>
          <Button
            onClick={downloadAllSQL}
            variant="outline" size="sm"
            className="text-xs border-emerald-700/50 text-emerald-400 hover:bg-emerald-950/40 gap-1.5"
          >
            <Lucide.Download size={13} /> Download .sql
          </Button>
          <Button
            onClick={generateAllSQL}
            disabled={generatingAll || loading || features.length === 0}
            size="sm"
            className="text-xs bg-emerald-700 hover:bg-emerald-600 text-white font-bold gap-1.5"
          >
            {generatingAll
              ? <><Lucide.Loader2 size={13} className="animate-spin" /> Generating Semua...</>
              : <><Lucide.Sparkles size={13} /> Generate Semua SQL (AI)</>}
          </Button>
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-y-auto bg-slate-950/95 p-6">
        {loading ? (
          <div className="flex flex-col items-center justify-center h-full min-h-[300px]">
            <Lucide.Loader2 size={32} className="animate-spin text-emerald-400" />
            <p className="mt-4 text-sm text-slate-400">Memuat data canvas...</p>
          </div>
        ) : features.length === 0 ? (
          <div className="flex flex-col items-center justify-center h-full min-h-[300px] gap-4">
            <div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-slate-800 text-slate-500">
              <Lucide.Database size={28} />
            </div>
            <div className="text-center">
              <p className="text-base font-semibold text-slate-300">Belum ada canvas</p>
              <p className="text-sm text-slate-500 mt-1">Generate feature canvas terlebih dahulu</p>
            </div>
            <Button onClick={() => navigate({ to: "/app/canvas" })} size="sm" className="text-xs gap-1.5">
              <Lucide.ArrowLeft size={13} /> Kembali ke Canvas
            </Button>
          </div>
        ) : (
          <div className="max-w-5xl mx-auto space-y-4">
            {/* Info Banner */}
            <div className="rounded-xl border border-emerald-900/50 bg-emerald-950/20 px-5 py-4 flex items-start gap-3">
              <Lucide.Info size={16} className="text-emerald-400 mt-0.5 shrink-0" />
              <div>
                <p className="text-xs font-semibold text-emerald-300">SQL Schema Generator</p>
                <p className="text-[11px] text-slate-400 mt-0.5">
                  Klik <span className="text-emerald-400 font-medium">"Generate SQL (AI)"</span> per modul untuk mendapatkan SQL schema lengkap hingga 5000 karakter dari Gemini + Groq. Atau klik <span className="text-emerald-400 font-medium">"Generate Semua SQL"</span> untuk semua modul sekaligus.
                </p>
              </div>
            </div>

            {/* Feature SQL Cards */}
            {features.map((feat, idx) => {
              const status = sqlStatuses[idx];
              const sqlContent = getFeatureSQL(idx);
              const isExpanded = expandedIdx === idx;
              const isGenerating = status?.status === "generating";
              const isDone = status?.status === "done";
              const isError = status?.status === "error";
              const tableCount = (feat.sqlSchema?.length ?? 0);

              return (
                <div
                  key={`sql-feat-${idx}`}
                  className="rounded-2xl border border-slate-800/70 bg-slate-900/50 overflow-hidden"
                >
                  {/* Card Header */}
                  <div
                    className="flex items-center justify-between px-5 py-4 cursor-pointer hover:bg-slate-800/30 transition"
                    onClick={() => setExpandedIdx(isExpanded ? null : idx)}
                  >
                    <div className="flex items-center gap-3">
                      <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-emerald-500/10 text-emerald-400 border border-emerald-900/50">
                        <Lucide.Database size={16} />
                      </div>
                      <div>
                        <div className="text-sm font-bold text-slate-200">{feat.name}</div>
                        <div className="flex items-center gap-2 mt-0.5">
                          <Badge className="text-[9px] bg-indigo-500/10 text-indigo-400 border border-indigo-500/20">
                            {feat.phase.split(":")[0]}
                          </Badge>
                          <span className="text-[10px] text-slate-500">{tableCount} tabel terencana</span>
                          {isDone && (
                            <span className="text-[10px] text-emerald-400 flex items-center gap-1">
                              <Lucide.CheckCircle size={10} /> AI Generated
                            </span>
                          )}
                          {isError && (
                            <span className="text-[10px] text-red-400 flex items-center gap-1">
                              <Lucide.AlertCircle size={10} /> Error
                            </span>
                          )}
                        </div>
                      </div>
                    </div>

                    <div className="flex items-center gap-2">
                      <button
                        onClick={(e) => { e.stopPropagation(); copySQL(idx); }}
                        className="flex items-center gap-1.5 rounded-lg border border-slate-700 bg-slate-800/60 px-3 py-1.5 text-[11px] font-medium text-slate-300 hover:bg-slate-700 transition"
                      >
                        {copiedIdx === idx ? <Lucide.Check size={11} className="text-emerald-400" /> : <Lucide.Copy size={11} />}
                        {copiedIdx === idx ? "Disalin!" : "Copy"}
                      </button>
                      <button
                        onClick={(e) => { e.stopPropagation(); generateSQLForFeature(idx); }}
                        disabled={isGenerating || generatingAll}
                        className="flex items-center gap-1.5 rounded-lg border border-emerald-700/50 bg-emerald-950/40 px-3 py-1.5 text-[11px] font-semibold text-emerald-300 hover:bg-emerald-900/50 transition disabled:opacity-50"
                      >
                        {isGenerating
                          ? <><Lucide.Loader2 size={11} className="animate-spin" /> Generating...</>
                          : <><Lucide.Sparkles size={11} /> Generate SQL (AI)</>}
                      </button>
                      <Lucide.ChevronDown
                        size={16}
                        className={`text-slate-500 transition-transform ${isExpanded ? "rotate-180" : ""}`}
                      />
                    </div>
                  </div>

                  {/* SQL Content (Expandable) */}
                  {isExpanded && (
                    <div className="border-t border-slate-800/60 bg-slate-950/50 p-4">
                      {isGenerating ? (
                        <div className="flex items-center gap-3 p-6 justify-center">
                          <Lucide.Loader2 size={20} className="animate-spin text-emerald-400" />
                          <div>
                            <p className="text-sm text-slate-300 font-medium">AI sedang generate SQL schema...</p>
                            <p className="text-xs text-slate-500 mt-0.5">Gemini + Groq berkolaborasi menghasilkan SQL lengkap</p>
                          </div>
                        </div>
                      ) : sqlContent ? (
                        <div className="rounded-xl border border-slate-800 bg-slate-950 p-4 font-mono text-[11px] text-emerald-300 overflow-x-auto whitespace-pre leading-relaxed max-h-[500px] overflow-y-auto">
                          {sqlContent}
                        </div>
                      ) : (
                        <div className="rounded-xl border border-slate-800/50 bg-slate-950/50 p-6 text-center">
                          <Lucide.Database size={24} className="text-slate-600 mx-auto mb-2" />
                          <p className="text-xs text-slate-500">Klik "Generate SQL (AI)" untuk generate SQL schema lengkap untuk modul ini</p>
                        </div>
                      )}

                      {/* Sub-features hint */}
                      {feat.subs.length > 0 && (
                        <div className="mt-3 flex flex-wrap gap-1.5">
                          {feat.subs.map((s) => (
                            <span key={s} className="inline-flex items-center gap-1 rounded-full bg-slate-800/60 border border-slate-700/40 px-2 py-0.5 text-[10px] text-slate-400">
                              <span className="h-1 w-1 rounded-full bg-indigo-500" /> {s}
                            </span>
                          ))}
                        </div>
                      )}
                    </div>
                  )}
                </div>
              );
            })}

            {/* Download CTA */}
            <div className="rounded-2xl border border-dashed border-slate-700/60 bg-slate-900/30 p-6 flex items-center justify-between">
              <div>
                <p className="text-sm font-semibold text-slate-200">Download semua SQL schemas</p>
                <p className="text-xs text-slate-500 mt-0.5">Ekspor seluruh SQL schema ke file .sql untuk digunakan langsung di database Anda</p>
              </div>
              <div className="flex gap-2">
                <Button onClick={copyAllSQL} variant="outline" size="sm" className="text-xs border-slate-700 gap-1.5">
                  <Lucide.Copy size={13} /> Copy Semua
                </Button>
                <Button onClick={downloadAllSQL} size="sm" className="text-xs bg-emerald-700 hover:bg-emerald-600 text-white gap-1.5">
                  <Lucide.Download size={13} /> Download .sql
                </Button>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
